### ISSUE TITLE
Windows環境でnifcloudコマンドが実行出来ない

### ISSUE THREAD

**Issue by kozm** [nifcloud/nifcloud-cli#15]
# 概要
Windows環境では、nifcloud.cmdなどのファイル名で実行ファイルが必要だが、現在はnifcloudという名前のpythonスクリプトしかなく、コマンドプロンプトからnifcloudコマンドが実行出来ない。

# 期待する結果
Windowsのコマンドプロンプトからnifcloudコマンドがそのまま実行出来る。

**Comment by aokumasan** [comment]
Thank you for feature request.

Windows MSI installer is now supported at v1.4.2 🎉 
Please see [README](https://github.com/nifcloud/nifcloud-cli/tree/v1.4.2#using-msi-installer-windows-only) 👀 

```
C:\>nifcloud --version
nifcloud-cli/1.4.2 Python/3.9.13 Windows/10 botocore/1.21.43
```
