### ISSUE TITLE
create-imageコマンドについて（About the create-image command）

### ISSUE THREAD

**Issue by nanami7030** [nifcloud/nifcloud-cli#29]
以下コマンドを実行することができません。何が原因でしょうか？

>set TODAY=%date:/=%
>nifty-create-image TESTServer --name TESTServer_%TODAY% -d TESTServer_%TODAY%_IMAGE
'nifty-create-image'は、内部コマンドまたは外部コマンド、操作可能なプログラムまたはバッチファイルとして認識されていません。

https://docs.nifcloud.com/cli/index.htm
上記の手順に従い最新のWindows用MSIインストーラを実行し
環境変数はnifcloud configureコマンドで設定し、
Windows: %UserProfile%\.nifcloud配下のファイルも確認済みです。
以下コマンドの実行結果も正常に表示されました。
・$ nifcloud --version
・$ nifcloud computing describe-instances

nifty-create-imageコマンドを実行するために
何か手順が不足しているようならご教示いただけますでしょうか？

I cannot execute the following command. What could be the cause?

>set TODAY=%date:/=%
>nifty-create-image TESTServer --name TESTServer_%TODAY% -d TESTServer_%TODAY%_IMAGE
'nifty-create-image' is not recognized as an internal or external command, operable program or batch file.

https://docs.nifcloud.com/cli/index.htm
Follow the above instructions to run the latest MSI installer for Windows and
Set environment variables with the nifcloud configure command,
Windows: %UserProfile%\.nifcloud files have also been checked.
The following commands were also successfully executed.
The following commands were also executed successfully: $ nifcloud --version
$ nifcloud computing describe-instances

If there are any missing steps to execute the nifty-create-image command, please let us know.
If there are any steps missing, please let us know.

**Comment by fuku2014** [comment]
@nanami7030

Hello!

The `nifty-create-image` command is an old CLI command.
To execute the command with this nifcloud-cli, write as follows.

```console
nifcloud computing create-image --instance-id TESTServer --name TESTServer_%TODAY% --description TESTServer_%TODAY%_IMAGE
```

See more information https://nifcloud-cli.readthedocs.io/en/latest/reference/computing/create-image.html .

Enjoy!

**Comment by nanami7030** [comment]
Thank you for your response.
Is it possible to run the following command to remove the custom image?
Please let me know if you have any suggestions, such as the command is outdated.

rem Write the ID of the created custom image to WEEK.txt
nifcloud computing create-image --instance-id MBSV23 --name MBSV23_%TODAY% --description MBSV23_%TODAY%_IMAGE > %WEEK%.txt

rem Enter environment variables
set WEEK=4
set /p ID=<%WEEK%.txt
nifcloud computing delete-image --instance-id %ID:IMAGE =%

ご回答いただき有難うございます。
以下コマンドを実行して、カスタムイメージを削除することは可能でしょうか？
コマンドが古い、などご指摘があれば教えてください。

rem 作成したカスタムイメージのIDをWEEK.txtに書き込む
nifcloud computing create-image --instance-id MBSV23 --name MBSV23_%TODAY% --description MBSV23_%TODAY%_IMAGE > %WEEK%.txt

rem 環境変数を入力
set WEEK=4
set /p ID=<%WEEK%.txt
nifcloud computing delete-image --instance-id %ID:IMAGE  =%

**Comment by fuku2014** [comment]
@nanami7030 

Hi!

> rem Write the ID of the created custom image to WEEK.txt

By default, nifcloud-cli outputs all response results.  
If you want to extract only the ImageId, it is best to use `--query` as follows.

```console
 nifcloud computing create-image --instance-id TESTServer  --name TESTServer --description TESTServer --output text --query ImageId
```
Please specify `--image-id` instead of `--instance-id` in delete-image.

https://nifcloud-cli.readthedocs.io/en/latest/reference/computing/delete-image.html

Enjoy 🚀
